
import { BlockInstance } from '../types/builderTypes';

/**
 * Extracts the HTML from the editor canvas, stripping editor-specific UI
 * and ensuring the data-attributes for state are preserved.
 */
export const serializeBlocksToHtml = (canvasElement: HTMLElement): string => {
  // Clone the canvas to avoid modifying the live editor
  const clone = canvasElement.cloneNode(true) as HTMLElement;

  // 1. Remove Editor Overlays
  const overlays = clone.querySelectorAll('.ui-overlay');
  overlays.forEach(el => el.remove());

  // 2. Extract the actual component wrappers
  // We look for our special class .builder-component
  const components = clone.querySelectorAll('.builder-component');

  const container = document.createElement('div');

  components.forEach(node => {
    // Clone the component node
    const nodeClone = node.cloneNode(true) as HTMLElement;

    // The parent wrapper in CanvasBlock has 'pointer-events-none' and 'select-none'.
    // We don't want those in the final HTML usually, but .builder-component is inside that.
    // So we just need to make sure the .builder-component itself is clean.
    // If .builder-component inherits styles that block interaction, we might want to reset them here.
    // But based on CanvasBlock.tsx, .builder-component is a plain div.

    container.appendChild(nodeClone);
  });

  return container.innerHTML;
};

/**
 * Parses an HTML string (previously generated by the builder)
 * and reconstructs the BlockInstance array from the data-attributes.
 */
export const parseHtmlToBlocks = (htmlString: string): BlockInstance[] => {
  const parser = new DOMParser();
  const doc = parser.parseFromString(htmlString, 'text/html');

  const components = doc.querySelectorAll('.builder-component');

  const blocks: BlockInstance[] = [];

  components.forEach((el) => {
    const templateName = el.getAttribute('data-template-name');
    const settingsRaw = el.getAttribute('data-settings');
    const contentRaw = el.getAttribute('data-content');
    const id = el.getAttribute('data-id'); // Recover ID if possible, else gen new

    if (templateName && settingsRaw && contentRaw) {
      try {
        blocks.push({
          id: id || crypto.randomUUID(),
          templateName: templateName,
          settings: JSON.parse(settingsRaw),
          content: JSON.parse(contentRaw)
        });
      } catch (e) {
        console.error("Failed to parse component data", e);
      }
    }
  });

  return blocks;
};
